import type { Metadata } from 'next'
import Image from 'next/image'
import natureBackground from '@/public/images/nature background.jpg'
import './globals.scss'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body>
                <div className='hero'>
                    <div className='backgroundWrapper'>
                        <Image
                            src={natureBackground}
                            alt='hero img'
                            className='background'
                        />
                    </div>
                    <h1 className='header'>EcoIndex</h1>
                </div>
                <main className='main'>{children}</main>
            </body>
        </html>
    )
}
